// generated version.h
#define EX_APP_ID_STR "{b9464f48-5337-57a6-aa1d-adc298f5233d}"
#define EX_APP_ID_OLD_STR "b9464f48-5337-57a6-aa1d-adc298f5233d"
#define EX_APP_NAME_STR "boardmix"
#define EX_APP_DISPLAY_NAME_STR "boardmix"
#define EX_APP_DISPLAY_VERSION_STR "boardmix"
#define EX_APP_BASE_DIR_STR ".\{app}"
#define EX_APP_TMP_DIR_STR ".\{tmp}"
#define EX_APP_LANG_DIR_STR ".\{lang}"
#define EX_APP_OUTPUT_DIR_STR ".\{output}"
#define EX_APP_SETUP_ICON_FILE_STR ".\setup.ico"
#define EX_COMPANY_NAME_STR "boardmix"
#define EX_COMPANY_URL_STR "https://boardmix.cn/"
#define EX_SUPPORT_URL_STR "https://boardmix.cn/contact-us/"
#define EX_UPDATES_URL_STR "https://boardmix.cn/releases/"
#define EX_CONTACT_STR "support@boardmix.cn"
#define EX_SUPPORT_PHONE_STR "0755-86665000"
#define EX_README_URL_STR "https://boardmix.cn/about-us/"
#define EX_POLICY_URL_STR "https://boardmix.cn/private-policy/"
#define EX_LICENSE_URL_STR "https://boardmix.cn/term-services/"
#define EX_COMMENTS_STR "boardmix是国内前沿的在线协作白板工具，集成了ai、思维导图、流程图、ppt、文档笔记和看板等创作能力，打通成员之间进行灵感采集、思考、创作、管理、演示、协作的全链路，支持2000+人实时协同，500+人实时编辑，boardmix一次性创新集成了 ai生图、ai一键ppt、ai 生成思维导图等 ai创作能力。"
#define EX_COPYRIGHT_STR "Copyright © 2023 BOSYUN TECHNOLOGY LIMITED. All rights reserved."
